//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contacto.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_contacto
    {
        public int idcontacto { get; set; }
        public string cedulaTitular { get; set; }
        public string cedulaContacto { get; set; }
    
        public virtual tb_usuario tb_usuario { get; set; }
        public virtual tb_usuario tb_usuario1 { get; set; }
    }
}
