//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contacto.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Celular
    {
        public int idcelular { get; set; }
        public string celular { get; set; }
        public bool principal { get; set; }
        public int idMedioContacto { get; set; }
    
        public virtual tb_medioContacto tb_medioContacto { get; set; }
    }
}
